Repository ros2/rviz, pull requests merged in 2018-06, with the labels that each got.

#279 add visibility control header, but don’t use it yet
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/visibility_control.hpp
Labels: in review

#288 work around libassimp-dev bug
  rviz_assimp_vendor/rviz_assimp_vendor-extras.cmake.in
Labels: bug, in review

#265 Make rviz_common::Panel public
  rviz_common/CMakeLists.txt
  rviz_common/include/rviz_common/panel.hpp
  rviz_common/src/rviz_common/displays_panel.cpp
  rviz_common/src/rviz_common/displays_panel.hpp
  rviz_common/src/rviz_common/failed_panel.hpp
  rviz_common/src/rviz_common/panel.cpp
  rviz_common/src/rviz_common/panel_factory.cpp
  rviz_common/src/rviz_common/panel_factory.hpp
  rviz_common/src/rviz_common/selection_panel.cpp
  rviz_common/src/rviz_common/selection_panel.hpp
  rviz_common/src/rviz_common/tool_properties_panel.cpp
  rviz_common/src/rviz_common/tool_properties_panel.hpp
  rviz_common/src/rviz_common/views_panel.cpp
  rviz_common/src/rviz_common/views_panel.hpp
  rviz_common/src/rviz_common/visualization_frame.cpp
  rviz_common/src/rviz_common/visualization_frame.hpp
Labels: in review

#272 Enable RViz application icon to be shown also on Mac
  rviz_common/src/rviz_common/visualization_frame.cpp
Labels: in review

#285 Fix names in plugin_descriptions
  rviz_default_plugins/plugins_description.xml
Labels: in review

#284 Fix segfault selection manager test
  rviz_common/test/display_context_fixture.cpp
  rviz_common/test/interaction/mock_selection_renderer.hpp
  rviz_common/test/interaction/selection_test_fixture.hpp
  rviz_default_plugins/test/rviz_default_plugins/displays/display_test_fixture.cpp
Labels: in review

#283 Fix select and measure tool behaviour on Mac Retina display
  rviz_common/include/rviz_common/viewport_mouse_event.hpp
  rviz_common/src/rviz_common/viewport_mouse_event.cpp
  rviz_rendering/src/rviz_rendering/render_system.cpp
Labels: in review

#282 Migrate XYOrbitViewController
  rviz/src/rviz/default_plugin/view_controllers/xy_orbit_view_controller.cpp
  rviz_common/src/rviz_common/frame_position_tracking_view_controller.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/view_controllers/orbit/orbit_view_controller.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/view_controllers/orbit/orbit_view_controller.cpp
  rviz_default_plugins/src/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.cpp
  rviz_default_plugins/src/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/orbit/orbit_view_controller_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/ortho/ortho_view_controller_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/view_controller_test_fixture.hpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller_test.cpp
  rviz_visual_testing_framework/src/internal/display_handler.cpp
Labels: :fire:, in review

#197 Use only a single ros node inside of rviz
  rviz_common/CMakeLists.txt
  rviz_common/include/rviz_common/display_context.hpp
  rviz_common/include/rviz_common/properties/ros_topic_property.hpp
  rviz_common/include/rviz_common/ros_integration/ros_client_abstraction.hpp
  rviz_common/include/rviz_common/ros_integration/ros_client_abstraction_iface.hpp
  rviz_common/include/rviz_common/ros_integration/ros_node_abstraction.hpp
  rviz_common/include/rviz_common/ros_integration/ros_node_abstraction_iface.hpp
  rviz_common/include/rviz_common/ros_topic_display.hpp
  rviz_common/include/rviz_common/visualizer_app.hpp
  rviz_common/src/rviz_common/add_display_dialog.cpp
  rviz_common/src/rviz_common/add_display_dialog.hpp
  rviz_common/src/rviz_common/displays_panel.cpp
  rviz_common/src/rviz_common/displays_panel.hpp
  rviz_common/src/rviz_common/panel_factory.cpp
  rviz_common/src/rviz_common/panel_factory.hpp
  rviz_common/src/rviz_common/properties/ros_topic_property.cpp
  rviz_common/src/rviz_common/ros_integration/ros_client_abstraction.cpp
  rviz_common/src/rviz_common/ros_integration/ros_node_abstraction.cpp
  rviz_common/src/rviz_common/ros_integration/ros_node_storage.cpp
  rviz_common/src/rviz_common/ros_integration/ros_node_storage.hpp
  rviz_common/src/rviz_common/ros_integration/ros_node_storage_iface.hpp
  rviz_common/src/rviz_common/visualization_frame.cpp
  rviz_common/src/rviz_common/visualization_frame.hpp
  rviz_common/src/rviz_common/visualization_manager.cpp
  rviz_common/src/rviz_common/visualization_manager.hpp
  rviz_common/src/rviz_common/visualizer_app.cpp
  rviz_common/test/mock_display_context.hpp
  rviz_common/test/ros_node_abstraction_test.cpp
  rviz_common/test/visualizer_app_test.cpp
  rviz_default_plugins/include/rviz_default_plugins/tools/point/point_tool.hpp
  rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/marker_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.cpp
  rviz_default_plugins/test/rviz_default_plugins/mock_display_context.hpp
Labels: :fire:, enhancement, in review

#292 Harmonise failed transform behaviour
  rviz_common/include/rviz_common/display.hpp
  rviz_common/src/rviz_common/display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/grid/grid_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/path/path_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud2_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_common.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/polygon/polygon_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose_array/pose_array_display.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/camera/camera_display_visual_test.cpp
Labels: in review

#266 Migrate focus tool
  rviz/src/rviz/default_plugin/tools/focus_tool.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/tools/move/move_tool.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/tools/focus/focus_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/focus/focus_tool.hpp
  rviz_default_plugins/src/rviz_default_plugins/tools/move/move_tool.cpp
Labels: :fire:, in review

#277 Fix splash screen and help panel
  rviz_common/CMakeLists.txt
  rviz_common/default.rviz
  rviz_common/help/help.html
  rviz_common/icons/classes/Help.svg
  rviz_common/images/splash.png
  rviz_common/images/splash_overlay.png
  rviz_common/include/rviz_common/display_context.hpp
  rviz_common/src/rviz_common/help_panel.cpp
  rviz_common/src/rviz_common/help_panel.hpp
  rviz_common/src/rviz_common/panel_factory.cpp
  rviz_common/src/rviz_common/selection_panel.hpp
  rviz_common/src/rviz_common/visualization_frame.cpp
  rviz_common/src/rviz_common/visualization_manager.hpp
  rviz_common/src/rviz_common/visualizer_app.cpp
  rviz_common/test/mock_display_context.hpp
  rviz_default_plugins/test/rviz_default_plugins/mock_display_context.hpp
Labels: :fire:, in review

#278 Migrate point stamped display
  rviz/src/rviz/default_plugin/point_display.cpp
  rviz/src/rviz/default_plugin/point_display.h
  rviz/src/rviz/default_plugin/point_visual.cpp
  rviz/src/rviz/default_plugin/point_visual.h
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/displays/point/point_stamped_display.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/displays/point/point_stamped_display.cpp
  rviz_default_plugins/test/reference_images/test_with_three_points_ref.png
  rviz_default_plugins/test/rviz_default_plugins/displays/point/point_stamped_display_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/point/point_stamped_display_visual_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/point_display_page_object.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/point_display_page_object.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/point_stamped_publisher.hpp
Labels: in review

#286 Migrate GridCellsDisplay
  rviz/src/rviz/default_plugin/grid_cells_display.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/displays/grid_cells/grid_cells_display.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/displays/grid_cells/grid_cells_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose_array/pose_array_display.cpp
  rviz_default_plugins/test/reference_images/grid_cells_display_visual_test_ref.png
  rviz_default_plugins/test/rviz_default_plugins/displays/grid_cells/grid_cells_display_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/grid_cells/grid_cells_display_visual_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/grid_cells_display_page_object.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/grid_cells_display_page_object.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/grid_cells_publisher.hpp
  rviz_rendering/include/rviz_rendering/objects/point_cloud.hpp
  rviz_rendering/src/rviz_rendering/objects/point_cloud.cpp
Labels: in review

#293 Fix visibility of xy_orbit_view_controller
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp
  rviz_default_plugins/src/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.cpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/orbit/orbit_view_controller_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller_test.cpp
Labels: in review

#298 Implement workaround for missing transform between identical frames
  rviz_common/src/rviz_common/frame_manager.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/grid/grid_display.cpp
Labels: in review

#299 Fix failing tests
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/test/rviz_default_plugins/displays/grid_cells/grid_cells_display_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/point/point_stamped_display_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/view_controllers/fps/fps_view_controller_test.cpp
  rviz_visual_testing_framework/src/internal/display_handler.cpp
Labels: in review

#300 Add help again
  rviz_common/default.rviz
  rviz_common/help/help.html
Labels: in review

#303 Update documentation and package.xml
  README.md
  migration_guide.md
  rviz2/package.xml
  rviz_common/package.xml
  rviz_default_plugins/package.xml
  rviz_rendering/package.xml
Labels: in review

#305 Fix warning in Debug mode
  rviz_default_plugins/src/rviz_default_plugins/displays/map/map_display.cpp
Labels: in review

#311 Warn on missing CameraInfo
  rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
Labels: in review

#310 Fix segfault for tf on windows
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/src/rviz_default_plugins/displays/tf/frame_info.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/tf/tf_display.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/tf/frame_info_test.cpp
Labels: in review

#307 Fix point cloud selection
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_common.cpp
Labels: in review

#314 Move selection icon to rviz_common
  rviz_common/icons/classes/Selection.png
Labels: in review

#313 Fix segfault on empty frame
  rviz_common/src/rviz_common/frame_manager.cpp
Labels: bug, in review

#318 Further documentation improvement
  README.md
  docs/FEATURES.md
  docs/migration_guide.md
  docs/plugin_development.md
Labels: in review

#319 Fix bugs causing RViz to crash on macOS
  rviz_common/include/rviz_common/render_panel.hpp
  rviz_common/src/rviz_common/render_panel.cpp
  rviz_rendering/include/rviz_rendering/render_window.hpp
  rviz_rendering/src/rviz_rendering/ogre_render_window_impl.cpp
  rviz_rendering/src/rviz_rendering/render_window.cpp
Labels: in review

#316 Make status non editable
  rviz_common/src/rviz_common/display.cpp
  rviz_common/src/rviz_common/properties/status_list.cpp
  rviz_common/src/rviz_common/visualization_manager.cpp
Labels: in review

#290 Make tf use the rviz ros node
  rviz_common/src/rviz_common/frame_manager.cpp
  rviz_common/src/rviz_common/frame_manager.hpp
  rviz_common/src/rviz_common/visualization_frame.cpp
Labels: in review

#320 Hide warning when disabling map display
  rviz_default_plugins/include/rviz_default_plugins/displays/map/map_display.hpp
  rviz_default_plugins/src/rviz_default_plugins/displays/map/map_display.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/map/map_display_test.cpp
Labels: in review

#306 Fix invalid color profile in PNGs
  rviz_common/icons/ok.png
  rviz_common/images/splash.png
  rviz_common/images/splash_overlay.png
Labels: in review

#315 Polish selection behaviour
  rviz_common/src/rviz_common/interaction/selection_handler.cpp
  rviz_default_plugins/include/rviz_default_plugins/displays/laser_scan/laser_scan_display.hpp
  rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud2_display.hpp
  rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud_common.hpp
  rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud_display.hpp
  rviz_default_plugins/include/rviz_default_plugins/displays/pose/pose_display.hpp
  rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/line_marker_base.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/points_marker.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud2_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_common.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display_selection_handler.cpp
Labels: in review

#308 Use conversions and alpha in other displays
  rviz_common/src/rviz_common/interaction/selection_manager.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/map/map_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/arrow_marker.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/marker_selection_handler.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/mesh_resource_marker.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/triangle_list_marker.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/odometry/odometry_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/point/point_stamped_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.cpp
  rviz_rendering/include/rviz_rendering/material_manager.hpp
  rviz_rendering/src/rviz_rendering/material_manager.cpp
  rviz_rendering/src/rviz_rendering/objects/line.cpp
Labels: in review

#321 Improve plugin development documentation
  README.md
  docs/plugin_development.md
Labels: in review

#324 fix dependecy name for eigen
  rviz_rendering/package.xml
Labels: :fire:, in review

#330 Add Qt dependency to testing packages.
  rviz_rendering_tests/package.xml
  rviz_visual_testing_framework/package.xml
Labels: in review

#331 move find_package or test dependencies to test block
  rviz_rendering/CMakeLists.txt
Labels: bug, in review
