Repository ros2/rviz, pull requests merged in 2018-08, with the labels that each got.

#343 Revert workaround for identity transform after geometry2 fix
  rviz_common/src/rviz_common/frame_manager.cpp
Labels: in review

#342 Always build all tests and skip execution if not supported
  rviz_common/CMakeLists.txt
  rviz_default_plugins/CMakeLists.txt
  rviz_rendering/CMakeLists.txt
  rviz_rendering/src/examples/rendering_example.cpp
  rviz_rendering/test/rviz_rendering/objects/covariance_visual_test.cpp
  rviz_rendering/test/rviz_rendering/objects/line_test.cpp
  rviz_rendering/test/rviz_rendering/objects/movable_text_test.cpp
  rviz_rendering_tests/CMakeLists.txt
Labels: in review

#326 cleanup dependencies for rviz_rendering_tests
  rviz_rendering/package.xml
Labels: enhancement, in review

#345 Fixes #341
  rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.cpp
Labels: in review

#340 Pass clock to tf2_ros::buffer
  rviz_common/src/rviz_common/visualization_frame.cpp
Labels: in progress

#344 Increase visual testing stability
  rviz_default_plugins/include/rviz_default_plugins/displays/grid_cells/grid_cells_display.hpp
  rviz_default_plugins/src/rviz_default_plugins/displays/grid_cells/grid_cells_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/image/image_display_visual_test.cpp
  rviz_rendering/include/rviz_rendering/objects/point_cloud.hpp
  rviz_rendering/src/rviz_rendering/objects/point_cloud.cpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/visual_test_publisher.hpp
Labels: in review

#329 Migrate pose estimate tool
  README.md
  rviz_common/default.rviz
  rviz_common/help/help.html
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/tools/focus/focus_tool.hpp
  rviz_default_plugins/include/rviz_default_plugins/tools/nav_goal/goal_tool.hpp
  rviz_default_plugins/include/rviz_default_plugins/tools/pose/pose_tool.hpp
  rviz_default_plugins/include/rviz_default_plugins/tools/pose_estimate/initial_pose_tool.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/tools/focus/focus_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/nav_goal/goal_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/pose/pose_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/pose_estimate/initial_pose_tool.cpp
Labels: in review

#325 Migrate Range Display
  README.md
  rviz/src/rviz/default_plugin/range_display.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/include/rviz_default_plugins/displays/range/range_display.hpp
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/displays/range/range_display.cpp
  rviz_default_plugins/test/reference_images/range_display_visual_test_ref.png
  rviz_default_plugins/test/rviz_default_plugins/displays/range/range_display_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/displays/range/range_display_visual_test.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/range_display_page_object.cpp
  rviz_default_plugins/test/rviz_default_plugins/page_objects/range_display_page_object.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/range_publisher.hpp
Labels: in review

#312 Add hotkeys (also to help)
  rviz_common/help/help.html
  rviz_default_plugins/src/rviz_default_plugins/tools/focus/focus_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/measure/measure_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.cpp
Labels: in review

#348 backport changes for bouncy patch release 2
  rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.cpp
Labels: in review
