Repository ros2/rviz, pull requests merged in 2018-05, with the labels that each got.

#261 Fix build error for ignored qualifiers warning/error on GCC8
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/triangle_list_marker.cpp
Labels: enhancement, in review

#258 Fix debug build on Mac
  rviz_common/CMakeLists.txt
  rviz_default_plugins/CMakeLists.txt
  rviz_rendering/CMakeLists.txt
  rviz_rendering/src/rviz_rendering/render_system.cpp
  rviz_rendering_tests/CMakeLists.txt
Labels: in review

#160 Fix build with yaml-cpp installed system-wise
  rviz_yaml_cpp_vendor/rviz_yaml_cpp_vendor-extras.cmake.in
Labels: enhancement, requires-changes

#251 Migrate tool properties panel
  rviz_common/CMakeLists.txt
  rviz_common/default.rviz
  rviz_common/icons/classes/Tool Properties.png
  rviz_common/include/rviz_common/properties/property_tree_widget.hpp
  rviz_common/src/rviz_common/panel_factory.cpp
  rviz_common/src/rviz_common/properties/property_tree_widget.cpp
  rviz_common/src/rviz_common/tool_properties_panel.cpp
  rviz_common/src/rviz_common/tool_properties_panel.hpp
Labels: in review

#252 Allow MarkerDisplay to be added `By Topic`
  rviz_default_plugins/plugins_description.xml
Labels: in review

#263 Add migration guide
  migration_guide.md
Labels: in review

#262 Migrate publish point tool
  rviz/src/rviz/default_plugin/tools/point_tool.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.hpp
Labels: in review

#255 Restore program options for RViz
  rviz_common/src/rviz_common/visualizer_app.cpp
  rviz_rendering/include/rviz_rendering/ogre_logging.hpp
  rviz_rendering/src/rviz_rendering/ogre_logging.cpp
  rviz_rendering/src/rviz_rendering/render_system.cpp
  rviz_visual_testing_framework/src/visual_test_fixture.cpp
Labels: in review

#273 Remove unused CMake vars passed to Ogre
  rviz_ogre_vendor/CMakeLists.txt
Labels: in review
