Repository ros2/rviz, pull requests merged in 2018-04, with the labels that each got.

#238 Migrate LaserScanDisplay
  rviz/src/rviz/default_plugin/laser_scan_display.cpp
  rviz_default_plugins/CMakeLists.txt
  rviz_default_plugins/package.xml
  rviz_default_plugins/plugins_description.xml
  rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.hpp
Labels: in review

#209 Introduce visual testing framework for RViz
  rviz_common/include/rviz_common/visualizer_app.hpp
  rviz_common/src/rviz_common/add_display_dialog.cpp
  rviz_common/src/rviz_common/displays_panel.cpp
  rviz_common/src/rviz_common/properties/property_tree_with_help.cpp
  rviz_common/src/rviz_common/visualization_frame.cpp
  rviz_common/src/rviz_common/visualization_frame.hpp
  rviz_common/src/rviz_common/visualizer_app.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
  rviz_rendering/include/rviz_rendering/render_window.hpp
  rviz_rendering/src/rviz_rendering/ogre_render_window_impl.cpp
  rviz_rendering/src/rviz_rendering/ogre_render_window_impl.hpp
  rviz_rendering/src/rviz_rendering/render_system.cpp
  rviz_rendering/src/rviz_rendering/render_window.cpp
  rviz_visual_testing_framework/CMakeLists.txt
  rviz_visual_testing_framework/docs/README.md
  rviz_visual_testing_framework/docs/documentation.md
  rviz_visual_testing_framework/docs/ref_sphere.png
  rviz_visual_testing_framework/docs/spheres_diff.png
  rviz_visual_testing_framework/docs/test_sphere.png
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/display_handler.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/executor.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/image_tester.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/rviz_scene_test.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/test_helpers.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/internal/visual_test.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/base_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/camera_display_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/grid_display_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/image_display_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/page_object_with_window.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/point_cloud_display_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/page_objects/polygon_display_page_object.hpp
  rviz_visual_testing_framework/include/rviz_visual_testing_framework/visual_test_fixture.hpp
  rviz_visual_testing_framework/package.xml
  rviz_visual_testing_framework/src/internal/display_handler.cpp
  rviz_visual_testing_framework/src/internal/executor.cpp
  rviz_visual_testing_framework/src/internal/image_tester.cpp
  rviz_visual_testing_framework/src/internal/rviz_scene_test.cpp
  rviz_visual_testing_framework/src/internal/test_helpers.cpp
  rviz_visual_testing_framework/src/internal/visual_test.cpp
  rviz_visual_testing_framework/src/page_objects/base_page_object.cpp
  rviz_visual_testing_framework/src/page_objects/camera_display_page_object.cpp
  rviz_visual_testing_framework/src/page_objects/grid_display_page_object.cpp
  rviz_visual_testing_framework/src/page_objects/image_display_page_object.cpp
  rviz_visual_testing_framework/src/page_objects/page_object_with_window.cpp
  rviz_visual_testing_framework/src/page_objects/point_cloud_display_page_object.cpp
  rviz_visual_testing_framework/src/page_objects/polygon_display_page_object.cpp
  rviz_visual_testing_framework/src/visual_test_fixture.cpp
  rviz_visual_testing_framework/test/example_nodes.hpp
  rviz_visual_testing_framework/test/example_test.cpp
  rviz_visual_testing_framework/test/reference_images/example_test_with_pointcloud_ref.png
  rviz_visual_testing_framework/visual_tests_default_config.rviz
Labels: enhancement, in progress

#243 hack to fix urdf include dirs again
  rviz_default_plugins/CMakeLists.txt
Labels: bug, in review

#257 Disable rendering tests on Mac when building debug.
  rviz_common/CMakeLists.txt
  rviz_default_plugins/CMakeLists.txt
  rviz_rendering/CMakeLists.txt
  rviz_rendering_tests/CMakeLists.txt
Labels: in review
