Repository ros2/rviz, pull requests merged in 2019-05, with the labels that each got.

#398 avoid deprecated publish signature
  rviz_default_plugins/test/rviz_default_plugins/publishers/map_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/point_cloud2_publisher.hpp
Labels: in review

#399 changes to avoid deprecated API's
  rviz_common/include/rviz_common/ros_topic_display.hpp
  rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/map/map_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/marker/marker_display.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/nav_goal/goal_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/point/point_tool.cpp
  rviz_default_plugins/src/rviz_default_plugins/tools/pose_estimate/initial_pose_tool.cpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/camera_info_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/fluid_pressure_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/grid_cells_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/illuminance_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/image_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/laser_scan_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/map_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/marker_array_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/marker_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/odometry_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/path_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/point_cloud2_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/point_cloud_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/point_stamped_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/pose_array_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/pose_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/range_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/relative_humidity_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/single_marker_publisher.hpp
  rviz_default_plugins/test/rviz_default_plugins/publishers/temperature_publisher.hpp
Labels: in progress

#380 Upgrade to OGRE 1.10.12 to get OSX fix for Sierra
  rviz_ogre_vendor/CMakeLists.txt
Labels: in review

#387 Update ROS node graph API
  rviz_common/src/rviz_common/add_display_dialog.cpp
  rviz_default_plugins/plugins_description.xml
Labels: bug, in review

#404 fix install destination of OGRE media resources which contain a dirname
  rviz_rendering/src/cmake/register_rviz_ogre_media_exports_hook.cmake
Labels: bug, in review
