Repository ros2/rviz, pull requests merged in 2020-07, with the labels that each got.

#577 use reference in range loops to avoid copy
  rviz_default_plugins/src/rviz_default_plugins/displays/interactive_markers/interactive_marker.cpp
  rviz_default_plugins/src/rviz_default_plugins/displays/interactive_markers/interactive_marker_display.cpp
Labels: bug

#586 Avoid hiding base class getRenderOperation in PointCloudRenderable
  rviz_rendering/include/rviz_rendering/objects/point_cloud_renderable.hpp
Labels: enhancement, in review

#569 Added covariance settings to set pose estimate
  rviz_default_plugins/include/rviz_default_plugins/tools/pose_estimate/initial_pose_tool.hpp
  rviz_default_plugins/src/rviz_default_plugins/tools/pose_estimate/initial_pose_tool.cpp
Labels: enhancement

#587 Pass through CMAKE_{C,CXX}_FLAGS to OGRE build
  rviz_ogre_vendor/CMakeLists.txt
Labels: in review
